version: "3.8"

services:
  db:
    image: postgres
    container_name: insure_db
    volumes:
      - insurance_pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: insure
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2nrm4dcw
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PGDATA: "/var/lib/postgresql/data/pgdata"
    restart: unless-stopped
#  es:
#    image: elasticsearch:7.17.0
#    container_name: insure_elastic
#    volumes:
#      - esdata:/usr/share/elasticsearch/data
#    ports:
#      - "9200:9200"
#    environment:
#      - discovery.type=single-node
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insure
    volumes:
      - .:/code
    command: ./docker_commands.sh
    environment:
      POSTGRES_NAME: insure
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2nrm4dcw
      POSTGRES_HOST: db
      POSTGRES_PORT: 5433
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - db
#      - es

volumes:
  insurance_pgdata:
