#version: "3.8"
#
#services:
#  web:
#    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    ports:
#      - "8000:8000"

version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: insure
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ...
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data: