version: "3.8"

services:
  db:
    image: postgres
    container_name: insure_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: insure
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2nrm4dcw
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PGDATA: "/var/lib/postgresql/data/pg_data"
    restart: unless-stopped
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: insure_elastic
    volumes:
      - es_data:/var/lib/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    restart: unless-stopped
    networks:
      - elastic
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insure
    volumes:
      - .:/code
    command: ./docker_commands.sh
    environment:
      POSTGRES_NAME: insure
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2nrm4dcw
      POSTGRES_HOST: db
      POSTGRES_PORT: 5433
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - db
      - es

volumes:
  pg_data:
  es_data:
    driver: local

networks:
  elastic:
#    driver: bridge