version: "3.8"

services:
  celery:
    restart: always
    container_name: celery
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "insure", "worker", "-l", "info"]
    volumes:
      - celery_data:/var/lib/cellery/data
  celery_beat:
    restart: always
    container_name: celery_beat
    build:
      context: .
      dockerfile: Dockerfile
    command: ["celery", "-A", "insure", "beat", "-l", "info"]
    volumes:
      - celery_data:/var/lib/cellery_beat/data
  rabbitmq:
    restart: always
    container_name: rabbitmq
    image: rabbitmq:3.9.9-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rebbitmq_data:/var/lib/rabbitmq/data
      - rebbitmq_log:/var/lig/rabbitmq/log
  db:
    image: postgres
    container_name: insure_db
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: insure
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2nrm4dcw
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      PGDATA: "/var/lib/postgresql/data/pg_data"
    restart: unless-stopped
  mongodb:
    image: mongo
    container_name: mongo_db
    volumes:
      - mongo_data:/var/lib/mongo_db/data
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo_admin
      MONGO_INITDB_DATABASE: mongo_db
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    container_name: insure_elastic
    volumes:
      - es_data:/var/lib/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    restart: unless-stopped
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insure
    volumes:
      - .:/code
    command: ./docker_commands.sh
    environment:
      POSTGRES_NAME: insure
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2nrm4dcw
      POSTGRES_HOST: db
      POSTGRES_PORT: 5433
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - db
      - mongodb
      - es

volumes:
  pg_data:
  es_data:
  celery_data:
  celery_beat:
  rebbitmq_data:
  rebbitmq_log:
  mongo_data:
