# Generated by Django 4.0.1 on 2022-02-01 16:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_companyuserprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='activation_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 3, 16, 26, 44, 702947, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='companyuserprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='активен'),
        ),
    ]
