# Generated by Django 4.0.1 on 2022-01-27 07:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150, verbose_name='фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='имя')),
                ('patronymic', models.CharField(blank=True, max_length=150, verbose_name='отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone_number', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message='Format: +79876543210', regex='^\\+7\\d{10,10}$')], verbose_name='телефон')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.product', verbose_name='продукт')),
            ],
            options={
                'verbose_name': 'отклики',
                'verbose_name_plural': 'отклики',
            },
        ),
    ]
