# Generated by Django 4.0.1 on 2022-01-28 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_productresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productresponse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.productoption', verbose_name='продукт'),
        ),
    ]
