# Generated by Django 4.0.1 on 2022-01-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_product_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='productoption',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='активна'),
        ),
    ]
