# Generated by Django 4.0.1 on 2022-02-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_productoption_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHit',
            fields=[
                ('_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=256, unique=True, verbose_name='url')),
                ('count', models.PositiveBigIntegerField(default=1, verbose_name='количество просмотров')),
            ],
            options={
                'db_table': 'mongodb',
            },
        ),
    ]
