# Generated by Django 4.0.1 on 2022-03-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_pagehit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productoption',
            options={'ordering': ['-id'], 'verbose_name': 'опции продукта', 'verbose_name_plural': 'опции продукта'},
        ),
        migrations.AddField(
            model_name='productresponse',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='активна'),
        ),
    ]
