# Generated by Django 4.0.1 on 2022-03-09 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_productresponse_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productresponse',
            options={'ordering': ['-is_active', '-created'], 'verbose_name': 'отклики', 'verbose_name_plural': 'отклики'},
        ),
        migrations.AddField(
            model_name='pagehit',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='изменен'),
        ),
    ]
