# Generated by Django 4.0.1 on 2022-03-14 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_productresponse_options_pagehit_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoption',
            name='term',
            field=models.PositiveIntegerField(verbose_name='срок в месяцах'),
        ),
    ]
